name: Spoliatus
description:
  GitHub action which extracts the minor and patch version of a SemVer version
  object.
author: Communi-Suggestu

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: command
  color: green

# Define your inputs here.
inputs:
  version:
    description: The version to extract the minor and patch version from.

# Define your outputs here.
outputs:
  minor:
    description: The minor version.
  patch:
    description: The patch version.
  joined:
    description: The minor and patch version joined by a dot.

runs:
  using: node20
  main: dist/index.js
